#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# Defragmenter
# Author: Shannon Smith
# Purpose: Launch the installed GTK application. Updates are managed by APT.

exec /usr/bin/linux-defragger-desktop "$@"
